#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:12.18.2

pipelines:
  default:
    - step:
      name: Install dependencies and Test
      caches:
        - node
      script:
        - npm install
        - npm test